# Generated by Django 5.0.6 on 2024-06-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.TextField(blank=True)),
                ('announced', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('build', models.TextField(blank=True)),
                ('sim', models.CharField(blank=True, max_length=100)),
                ('display_type', models.CharField(blank=True, max_length=100)),
                ('display_size', models.CharField(blank=True, max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=100)),
                ('protection', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('chipset', models.CharField(blank=True, max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('gpu', models.CharField(blank=True, max_length=100)),
                ('card_slot', models.CharField(blank=True, max_length=100)),
                ('internal', models.CharField(blank=True, max_length=100)),
                ('main_camera', models.TextField(blank=True)),
                ('main_camera_features', models.TextField(blank=True)),
                ('main_camera_video', models.TextField(blank=True)),
                ('selfie_camera', models.TextField(blank=True)),
                ('selfie_camera_features', models.TextField(blank=True)),
                ('selfie_camera_video', models.TextField(blank=True)),
                ('loudspeaker', models.CharField(blank=True, max_length=100)),
                ('headphone_jack', models.CharField(blank=True, max_length=100)),
                ('wlan', models.CharField(blank=True, max_length=100)),
                ('bluetooth', models.CharField(blank=True, max_length=100)),
                ('positioning', models.CharField(blank=True, max_length=100)),
                ('nfc', models.CharField(blank=True, max_length=100)),
                ('radio', models.CharField(blank=True, max_length=100)),
                ('usb', models.CharField(blank=True, max_length=100)),
                ('sensors', models.TextField(blank=True)),
                ('battery_type', models.CharField(blank=True, max_length=100)),
                ('charging', models.TextField(blank=True)),
                ('colors', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('sar', models.CharField(blank=True, max_length=100)),
                ('sar_eu', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('performance', models.TextField(blank=True)),
                ('display', models.TextField(blank=True)),
                ('camera', models.CharField(blank=True, max_length=100)),
                ('loudness', models.CharField(blank=True, max_length=100)),
                ('battery', models.CharField(blank=True, max_length=100)),
                ('battery_new', models.CharField(blank=True, max_length=100)),
                ('others', models.CharField(default=None, max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('phone_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.phonename')),
            ],
        ),
    ]
